server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux: # You MUST add this level for the WebFlux starter in Boot 4
          routes:
            - id: task-manager-monolith
              uri: http://localhost:9090
              predicates:
                - Path=/api/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:9090"
            allowedMethods: ["GET", "POST", "PUT", "DELETE"]
